# Generated by Django 5.2.8 on 2025-11-24 10:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Назва філії')),
                ('code', models.SlugField(help_text="Коротке імʼя для URL, наприклад: 'center', 'left-bank'", unique=True, verbose_name='Код (slug)')),
                ('city', models.CharField(default='Дніпро', max_length=100, verbose_name='Місто')),
                ('address', models.CharField(max_length=255, verbose_name='Адреса')),
                ('phone_main', models.CharField(blank=True, max_length=50, verbose_name='Основний телефон')),
                ('phone_additional', models.CharField(blank=True, max_length=50, verbose_name='Додатковий телефон')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, help_text='Наприклад: 48.463020', max_digits=9, null=True, verbose_name='Широта (lat)')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, help_text='Наприклад: 35.045727', max_digits=9, null=True, verbose_name='Довгота (lng)')),
                ('map_link', models.URLField(blank=True, help_text='https://maps.google.com/...', verbose_name='Посилання на карту (Google/Apple)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активний філіал')),
                ('sort_order', models.PositiveIntegerField(default=10, verbose_name='Порядок сортування')),
            ],
            options={
                'verbose_name': 'Філіал',
                'verbose_name_plural': 'Філіали',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Назва послуги')),
                ('description', models.TextField(blank=True, verbose_name='Опис')),
                ('duration_min', models.PositiveIntegerField(default=30, help_text='Скільки хвилин триває прийом', verbose_name='Тривалість (хвилин)')),
                ('price_from', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Ціна від')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна послуга')),
            ],
            options={
                'verbose_name': 'Послуга',
                'verbose_name_plural': 'Послуги',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BranchWorkHour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.IntegerField(choices=[(0, 'Понеділок'), (1, 'Вівторок'), (2, 'Середа'), (3, 'Четвер'), (4, 'Пʼятниця'), (5, 'Субота'), (6, 'Неділя')], verbose_name='День тижня')),
                ('opens_at', models.TimeField(blank=True, null=True, verbose_name='Початок роботи')),
                ('closes_at', models.TimeField(blank=True, null=True, verbose_name='Кінець роботи')),
                ('is_closed', models.BooleanField(default=False, verbose_name='Вихідний')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_hours', to='booking.branch', verbose_name='Філіал')),
            ],
            options={
                'verbose_name': 'Години роботи',
                'verbose_name_plural': 'Години роботи',
                'ordering': ['branch', 'weekday'],
                'unique_together': {('branch', 'weekday')},
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='ПІБ пацієнта')),
                ('phone', models.CharField(max_length=30, verbose_name='Телефон')),
                ('is_first_visit', models.BooleanField(default=True, verbose_name='Перший візит')),
                ('date', models.DateField(verbose_name='Дата візиту')),
                ('time', models.TimeField(verbose_name='Час візиту')),
                ('status', models.CharField(choices=[('new', 'Нова заявка'), ('confirmed', 'Підтверджено'), ('completed', 'Завершено'), ('cancelled', 'Скасовано'), ('no_show', 'Пацієнт не зʼявився')], default='new', max_length=20, verbose_name='Статус')),
                ('note', models.TextField(blank=True, verbose_name='Коментар / опис проблеми')),
                ('internal_comment', models.TextField(blank=True, verbose_name='Внутрішній коментар для адміністраторів')),
                ('source', models.CharField(choices=[('website', 'Сайт'), ('phone', 'Дзвінок'), ('instagram', 'Instagram'), ('facebook', 'Facebook'), ('viber', 'Viber'), ('telegram', 'Telegram'), ('other', 'Інше')], default='website', max_length=20, verbose_name='Джерело заявки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='booking.branch', verbose_name='Філіал')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='booking.service', verbose_name='Послуга')),
            ],
            options={
                'verbose_name': 'Запис',
                'verbose_name_plural': 'Записи',
                'ordering': ['-date', '-time', '-created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status__in', ['new', 'confirmed'])), fields=('branch', 'date', 'time'), name='unique_slot_per_branch_for_active_statuses')],
            },
        ),
    ]
