# Generated by Django 5.2.8 on 2025-11-24 10:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='ПІБ лікаря')),
                ('specialization', models.CharField(blank=True, max_length=255, verbose_name='Спеціалізація')),
                ('room', models.CharField(blank=True, max_length=50, verbose_name='Кабінет')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='Робочий телефон')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активний лікар')),
            ],
            options={
                'verbose_name': 'Лікар',
                'verbose_name_plural': 'Лікарі',
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='DoctorSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.IntegerField(choices=[(0, 'Понеділок'), (1, 'Вівторок'), (2, 'Середа'), (3, 'Четвер'), (4, 'Пʼятниця'), (5, 'Субота'), (6, 'Неділя')], verbose_name='День тижня')),
                ('start_time', models.TimeField(verbose_name='Початок прийому')),
                ('end_time', models.TimeField(verbose_name='Кінець прийому')),
                ('is_active', models.BooleanField(default=True, verbose_name='Працює в цей день')),
            ],
            options={
                'verbose_name': 'Графік лікаря',
                'verbose_name_plural': 'Графік лікарів',
                'ordering': ['doctor', 'weekday'],
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='ПІБ')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Дата народження')),
                ('phone', models.CharField(max_length=30, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
            ],
            options={
                'verbose_name': 'Пацієнт',
                'verbose_name_plural': 'Пацієнти',
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='PatientDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Назва документа')),
                ('file', models.FileField(upload_to='patient_docs/%Y/%m/', verbose_name='Файл')),
                ('description', models.TextField(blank=True, verbose_name='Опис')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
            ],
            options={
                'verbose_name': 'Документ пацієнта',
                'verbose_name_plural': 'Документи пацієнтів',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='appointment',
            name='unique_slot_per_branch_for_active_statuses',
        ),
        migrations.AlterField(
            model_name='appointment',
            name='full_name',
            field=models.CharField(max_length=255, verbose_name='ПІБ пацієнта (на момент запису)'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doctors', to='booking.branch', verbose_name='Основний філіал'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='user',
            field=models.OneToOneField(help_text='Акаунт лікаря для входу в систему', on_delete=django.db.models.deletion.CASCADE, related_name='doctor_profile', to=settings.AUTH_USER_MODEL, verbose_name='Користувач'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='booking.doctor', verbose_name='Лікар'),
        ),
        migrations.AddField(
            model_name='doctorschedule',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_schedules', to='booking.branch', verbose_name='Філіал'),
        ),
        migrations.AddField(
            model_name='doctorschedule',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='booking.doctor', verbose_name='Лікар'),
        ),
        migrations.AddField(
            model_name='patient',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patients', to='booking.branch', verbose_name='Основний філіал'),
        ),
        migrations.AddField(
            model_name='patient',
            name='user',
            field=models.OneToOneField(blank=True, help_text='Опціонально: якщо у пацієнта є логін на сайті', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patient_profile', to=settings.AUTH_USER_MODEL, verbose_name='Користувач'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='booking.patient', verbose_name='Пацієнт'),
        ),
        migrations.AddConstraint(
            model_name='appointment',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['new', 'confirmed'])), fields=('branch', 'doctor', 'date', 'time'), name='unique_slot_per_doctor_branch_for_active_statuses'),
        ),
        migrations.AddField(
            model_name='patientdocument',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='booking.patient', verbose_name='Пацієнт'),
        ),
        migrations.AddField(
            model_name='patientdocument',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_patient_documents', to=settings.AUTH_USER_MODEL, verbose_name='Хто завантажив'),
        ),
        migrations.AlterUniqueTogether(
            name='doctorschedule',
            unique_together={('doctor', 'weekday', 'branch')},
        ),
    ]
