# Generated by Django 5.2.8 on 2025-11-25 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_doctor_doctorschedule_patient_patientdocument_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='bio',
            field=models.TextField(blank=True, help_text='Кілька речень про лікаря для зворотньої сторони картки', verbose_name='Короткий опис'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='Дата народження'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='experience_years',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Стаж (років)'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='photo',
            field=models.ImageField(blank=True, help_text='Горизонтальне фото 1200×400 у біло-блакитних тонах', null=True, upload_to='doctors/photos/', verbose_name='Фото лікаря'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='short_title',
            field=models.CharField(blank=True, help_text='Наприклад: Лікар-стоматолог, ортодонт', max_length=255, verbose_name='Посада / роль'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='skills',
            field=models.CharField(blank=True, help_text='Через кому: імплантація, ортопедія, терапія', max_length=255, verbose_name='Ключові навички'),
        ),
    ]
