# Generated by Django 5.2.8 on 2025-11-25 11:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_doctor_bio_doctor_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctorschedule',
            options={'ordering': ['doctor', 'weekday'], 'verbose_name': 'Тижневий графік лікаря', 'verbose_name_plural': 'Тижневі графіки лікарів'},
        ),
        migrations.AlterField(
            model_name='doctor',
            name='photo',
            field=models.ImageField(blank=True, help_text='Фото лікаря (буде автоматично конвертовано у WEBP)', null=True, upload_to='doctors/', verbose_name='Фото лікаря'),
        ),
        migrations.AlterField(
            model_name='doctorschedule',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_weekly_schedules', to='booking.branch', verbose_name='Філіал'),
        ),
        migrations.AlterField(
            model_name='doctorschedule',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_schedules', to='booking.doctor', verbose_name='Лікар'),
        ),
        migrations.CreateModel(
            name='DoctorDaySchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('start_time', models.TimeField(blank=True, null=True, verbose_name='Початок прийому')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='Кінець прийому')),
                ('is_working', models.BooleanField(default=True, help_text='Якщо зняти галочку — лікар у відпустці / лікар не приймає.', verbose_name='Працює у цей день')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='Примітка')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_day_schedules', to='booking.branch', verbose_name='Філіал')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='day_schedules', to='booking.doctor', verbose_name='Лікар')),
            ],
            options={
                'verbose_name': 'Денний графік лікаря',
                'verbose_name_plural': 'Денні графіки лікарів',
                'ordering': ['date', 'doctor'],
                'unique_together': {('doctor', 'branch', 'date')},
            },
        ),
    ]
