# Generated by Django 5.2.8 on 2025-11-25 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_alter_doctorschedule_options_alter_doctor_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctordayschedule',
            name='break_end',
            field=models.TimeField(blank=True, null=True, verbose_name='Кінець обіду'),
        ),
        migrations.AddField(
            model_name='doctordayschedule',
            name='break_start',
            field=models.TimeField(blank=True, null=True, verbose_name='Початок обіду'),
        ),
        migrations.AddField(
            model_name='doctorschedule',
            name='break_end',
            field=models.TimeField(blank=True, null=True, verbose_name='Кінець обіду'),
        ),
        migrations.AddField(
            model_name='doctorschedule',
            name='break_start',
            field=models.TimeField(blank=True, null=True, verbose_name='Початок обіду'),
        ),
    ]
