# Generated by Django 5.2.8 on 2025-11-25 14:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_doctordayschedule_break_end_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TreatmentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Назва категорії')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True, verbose_name='URL-ключ')),
                ('image', models.ImageField(blank=True, help_text='Фото напряму лікування. Якщо не у WEBP, буде автоматично конвертовано.', null=True, upload_to='treatments/', verbose_name='Зображення')),
                ('short_description', models.TextField(help_text='Використовується на картці (2–3 речення).', max_length=400, verbose_name='Короткий опис')),
                ('full_description', models.TextField(help_text='Основний текст статті для окремої сторінки.', verbose_name='Повний опис')),
                ('point_1', models.CharField(blank=True, max_length=255, verbose_name='Пункт 1')),
                ('point_2', models.CharField(blank=True, max_length=255, verbose_name='Пункт 2')),
                ('point_3', models.CharField(blank=True, max_length=255, verbose_name='Пункт 3')),
                ('point_4', models.CharField(blank=True, max_length=255, verbose_name='Пункт 4')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок сортування')),
                ('is_active', models.BooleanField(default=True, verbose_name='Показувати на сайті')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Створено')),
                ('services', models.ManyToManyField(blank=True, related_name='treatment_categories', to='booking.service', verbose_name="Пов'язані послуги")),
            ],
            options={
                'verbose_name': 'Категорія лікування',
                'verbose_name_plural': 'Категорії лікування',
                'ordering': ['sort_order', '-created_at'],
            },
        ),
    ]
