# Generated by Django 5.2.8 on 2025-11-26 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_treatmentcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=15, help_text='Наприклад: 48.46371481421031', max_digits=18, null=True, verbose_name='Широта (lat)'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=15, help_text='Наприклад: 35.05316031300193', max_digits=18, null=True, verbose_name='Довгота (lng)'),
        ),
    ]
